SET SERVEROUTPUT ON
SET VERIFY OFF
DECLARE
	A NUMBER:=&NUMBER_1;
	B NUMBER:=&NUMBER_2;
	S NUMBER;
BEGIN
	
	S:=A/B;
	DBMS_OUTPUT.PUT_LINE(S);
EXCEPTION WHEN ZERO_DIVIDE THEN
	DBMS_OUTPUT.PUT_LINE('DIVISION BY ZERO IS NOT POSSIBLE');
END;
/