SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
	AGE NUMBER(2):=&AGE;
BEGIN
	IF AGE>=18 THEN
		DBMS_OUTPUT.PUT_LINE('ELIGIBLE');
	ELSE
		DBMS_OUTPUT.PUT_LINE('NOT ELIGIBLE');
	END IF;
END;
/