SET SERVEROUTPUT ON;
DECLARE
	VSAL NUMBER;
	VENAME VARCHAR2(20);
BEGIN
	SELECT ENAME,SAL INTO VENAME,VSAL 
	FROM EMP
	WHERE EMPNO=7900;
	DBMS_OUTPUT.PUT_LINE('NAME OF THE EMLOYEE NUMBER 7900 IS:'||VENAME);
	DBMS_OUTPUT.PUT_LINE('SALARY OF THE EMLOYEE NUMBER 7900 IS:'||VSAL);
END;
/