SET SERVEROUTPUT ON;
DECLARE 
	VENAME VARCHAR(20);
BEGIN
	SELECT ENAME INTO VENAME
	FROM EMP
	WHERE EMPNO=7900;

	DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME WITH EMPLOYEE NUMBER 7900 IS '||VENAME);
END;
/