SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
	A NUMBER(3):=&NUMBER1;
	B NUMBER(3):=&NUMBER2;
	C NUMBER(3):=&NUMBER3;
BEGIN
	IF A>B AND A>C THEN
		DBMS_OUTPUT.PUT_LINE(A||' IS GREATEST');
	ELSIF B>A AND B>C THEN
		DBMS_OUTPUT.PUT_LINE(B||' IS GREATEST');
	ELSE
		DBMS_OUTPUT.PUT_LINE(C||' IS GREATEST');
	END IF;
END;
/
