SET SERVEROUTPUT ON;

DECLARE 
	VSAL NUMBER;
	VENAME SCOTT.EMP.ENAME%TYPE;
BEGIN
	SELECT SCOTT.EMP.SAL,SCOTT.EMP.ENAME INTO VSAL,VENAME
	FROM SCOTT.EMP
	WHERE SCOTT.EMP.EMPNO=7900;

	DBMS_OUTPUT.PUT_LINE(VSAL||VENAME);
END;
/